services:
  - type: web
    name: sistema-mudas
    env: python
    buildCommand: |
      pip install -r requirements.txt
      ./build.sh
    startCommand: gunicorn mudas_project.wsgi:application
    staticPublishPath: staticfiles
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mudas_project.settings
      - key: PYTHON_VERSION
        value: 3.12