services:
  - type: web
    name: sistema-mudas
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mudas_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mudas_project.settings
      - key: PYTHON_VERSION
        value: 3.12