# Generated by Django 5.2.1 on 2025-05-22 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Especie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("dias_ate_muda", models.PositiveIntegerField()),
                ("dias_ate_flor", models.PositiveIntegerField()),
                ("preco_muda", models.DecimalField(decimal_places=2, max_digits=6)),
                ("preco_flor", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name="MudaPlantada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_plantio", models.DateField()),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "especie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogo.especie",
                    ),
                ),
            ],
        ),
    ]
